version: '3.8'
services:
    oai-ext-dn:
        privileged: true
        init: true
        container_name: oai-ext-dn
        build: ./
        image: docker_ubuntu_focal
        volumes:
            - ./entrypoint.sh:/tmp/entrypoint.sh
        entrypoint: ./tmp/entrypoint.sh
        network_mode: host  
